const mongoose=require('mongoose')

const orderSchema=new mongoose.Schema({
    shippingInfo:{
        address:{
            type:String,
            required:true
        },
        country:{
            type:String,
            required:true
        },
        city:{
            type:String,
            required:true
        },
        state:{
            type:String
        },
        phoneno:{
            type:String,
            required:true
        },
        postalCode:{
            type:String,
            required:true
        }
    },
    user:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"user"
    },
    orderItems:[
        {
        product:{
            type:mongoose.Schema.Types.ObjectId,
            required:true,
            ref:'"product'
        },
        name:{
            type:String,
            required:true
        },
        price:{
            type:Number,
            required:true
        },
        quantity:{
            type:Number,
            required:true
        },
        image:{
            type:String,
            required:true
        }
    }],
    itemsPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    taxPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    shippingPrice:{
        type:Number,
        required:true,
        default:0.0
    },
    totalPrice:{
        type:Number,
        default:0.0
    },
    paymentDetail:{
        id:String,
        status:String
    },
    orderStatus:{
        type:String,
        default:"Processing"
    },
    paidAt:{
        type:String
    },
    deliveryAt:{
        type:String
    },
    createdAt:{
        type:Date,
        default:Date.now
    }

})
const orderModel=mongoose.model('order',orderSchema)

module.exports=orderModel